version: 2

updates:
    -   package-ecosystem: maven
        directory: "/"
        schedule:
            interval: weekly
            day: "sunday"
            time: "04:00"
        cooldown:
            default-days: 4
        open-pull-requests-limit: 10
        labels:
            - "dependencies"
            - "maven"
        groups:
            maven-minor-patch:
                update-types:
                    - "minor"
                    - "patch"
            maven-major:
                update-types:
                    - "major"

    -   package-ecosystem: github-actions
        directory: "/"
        schedule:
            interval: weekly
            day: "sunday"
            time: "04:00"
        cooldown:
            default-days: 4
        labels:
            - "dependencies"
            - "github-actions"
        groups:
            actions-minor-patch:
                update-types:
                    - "minor"
                    - "patch"
            actions-major:
                update-types:
                    - "major"
