apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: gjenlevende-bs-sak
  namespace: etterlatte

spec:
  image: {{ image }}
  ingresses:
    - https://gjenlevende-bs-sak.intern.dev.nav.no
  port: 8080
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 256Mi
  secureLogs:
    enabled: true
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    inbound:
      rules:
        - application: gjenlevende-bs-infotrygd
    outbound:
      rules:
        - application: gjenlevende-bs-infotrygd
