apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: gjenlevende-bs-sak
  namespace: etterlatte

spec:
  # Application konfigurasjon
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      memory: 512Mi

  # Nettverk
  ingresses:
    - https://gjenlevende-bs-sak.intern.dev.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: gjenlevende-bs-infotrygd
    outbound:
      rules:
        - application: gjenlevende-bs-infotrygd

  # Helse
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    failureThreshold: 10

  # Logging
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  secureLogs:
    enabled: true
