apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: gjenlevende-bs-sak
  namespace: etterlatte
spec:
  ingresses:
    - https://gjenlevende-bs-sak.intern.dev.nav.no
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  ttl: 3h
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 1024Mi