apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: gjenlevende-bs-sak
    namespace: etterlatte

spec:
    # Applikasjon konfigurasjon
    image: {{ image }}
    port: 8080
    replicas:
        min: 2
        max: 2
    leaderElection: true
    resources:
        requests:
            cpu: 162m
            memory: 448Mi
        limits:
            memory: 512Mi
    env:
        -   name: SPRING_PROFILES_ACTIVE
            value: dev
    gcp:
        sqlInstances:
            -   name: gjenlevende-bs-sak
                type: POSTGRES_17
                tier: db-g1-small
                diskAutoresize: true
                cascadingDelete: false
                highAvailability: false
                pointInTimeRecovery: true
                maintenance:
                    day: 7
                    hour: 23
                databases:
                    -   name: gjenlevende-bs-sak
                        envVarPrefix: DB

    # Nettverk
    ingresses:
        - https://gjenlevende-bs-sak.intern.dev.nav.no
    accessPolicy:
        inbound:
            rules:
                -   application: gjenlevende-bs-sak-frontend
                -   application: gjenlevende-bs-sak-frontend-lokal
                -   application: etterlatte-prosessering
        outbound:
            rules:
                -   application: gjenlevende-bs-sak-frontend
                -   application: gjenlevende-bs-sak-frontend-lokal

                    # Team Logs
                -   application: logging
                    namespace: nais-system
            external:
                -   host: gjenlevende-bs-infotrygd.dev-fss-pub.nais.io
                -   host: etterlatte-unleash-api.nav.cloud.nais.io
                -   host: saf-q2.dev-fss-pub.nais.io

    # Toggle
    envFrom:
        -   secret: gjenlevende-bs-sak-unleash-api-token

    # Helse
    liveness:
        path: /internal/health/liveness
        initialDelay: 30
        failureThreshold: 10
    readiness:
        path: /internal/health/readiness
        initialDelay: 30
        failureThreshold: 10

    # Logging
    prometheus:
        enabled: true
        path: /internal/prometheus
    observability:
        autoInstrumentation:
            enabled: true
            runtime: java
        logging:
            destinations:
                -   id: loki
                -   id: elastic

    # Autentisering
    azure:
        application:
            enabled: true
            tenant: trygdeetaten.no
            claims:
                groups:
                    -   id: 8df38a8c-6b34-49d7-b837-cefb153a03e8 # 0000-CA-Gjenlevende-BS-Saksbehandler
                    -   id: f9837eec-8d85-4f61-b89e-677e168fdf2f # 0000-CA-Gjenlevende-BS-Beslutter
                    -   id: 8c98e41f-4370-46e6-998a-2190c7f935bc # 0000-CA-Gjenlevende-BS-Veileder
                    -   id: 928636f4-fd0d-4149-978e-a6fb68bb19de # prosessering.rolle - (0000-GA-STDAPPS)
                extra:
                    - "NAVident"
                    - "azp_name"
            replyURLs:
                - https://gjenlevende-bs-sak.intern.dev.nav.no/swagger-ui/oauth2-redirect.html
            singlePageApplication: true
