# Unleash API Token
# Denne trenger kun å deployes en gang per endring
# For å deploye kan Nais dev yaml kan utvides:
#       RESOURCE: .nais/dev.yaml, .nais/unleash-apitoken.yaml

apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
    name: gjenlevende-bs-sak
    namespace: etterlatte
    labels:
        team: etterlatte
spec:
    unleashInstance:
        apiVersion: unleash.nais.io/v1
        kind: RemoteUnleash
        name: etterlatte
    secretName: gjenlevende-bs-sak-unleash-api-token

    # Specify which environment the API token should be created for.
    # Can be one of: development, or production.
    environment: development
